packages:
  - apps/docs
  - apps/web
  - apps/api
  - apps/api2
  - packages/database
  - packages/infra
  - packages/evm
  - packages/shared
ignoredBuiltDependencies:
  - '@reown/appkit'
  - bigint-buffer
  - keccak
  - sharp
