// エラーコード定数

export const ERROR_CODES = {
  // リソースが見つからない系
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",

  // 認証・認可系
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_TOKEN: "INVALID_TOKEN",
  INVALID_SESSION: "INVALID_SESSION",
  REQUIRES_ADDITIONAL_AUTH: "REQUIRES_ADDITIONAL_AUTH",

  // 決済系
  NONCE_USED: "NONCE_USED",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  SIGNATURE_INVALID: "SIGNATURE_INVALID",

  // バリデーション系
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_PARAMETER: "INVALID_PARAMETER",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
